/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/appointment-detail`; params?: Router.UnknownInputParams; } | { pathname: `/appointments`; params?: Router.UnknownInputParams; } | { pathname: `/compare-properties`; params?: Router.UnknownInputParams; } | { pathname: `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/help-center`; params?: Router.UnknownInputParams; } | { pathname: `/property-details`; params?: Router.UnknownInputParams; } | { pathname: `/recently-viewed`; params?: Router.UnknownInputParams; } | { pathname: `/saved-searches`; params?: Router.UnknownInputParams; } | { pathname: `/schedule-visit`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/shared-property`; params?: Router.UnknownInputParams; } | { pathname: `/whatsapp-contacts`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/appointment-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/appointments`; params?: Router.UnknownOutputParams; } | { pathname: `/compare-properties`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/help-center`; params?: Router.UnknownOutputParams; } | { pathname: `/property-details`; params?: Router.UnknownOutputParams; } | { pathname: `/recently-viewed`; params?: Router.UnknownOutputParams; } | { pathname: `/saved-searches`; params?: Router.UnknownOutputParams; } | { pathname: `/schedule-visit`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/shared-property`; params?: Router.UnknownOutputParams; } | { pathname: `/whatsapp-contacts`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/favorites` | `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/appointment-detail${`?${string}` | `#${string}` | ''}` | `/appointments${`?${string}` | `#${string}` | ''}` | `/compare-properties${`?${string}` | `#${string}` | ''}` | `/edit-profile${`?${string}` | `#${string}` | ''}` | `/help-center${`?${string}` | `#${string}` | ''}` | `/property-details${`?${string}` | `#${string}` | ''}` | `/recently-viewed${`?${string}` | `#${string}` | ''}` | `/saved-searches${`?${string}` | `#${string}` | ''}` | `/schedule-visit${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/shared-property${`?${string}` | `#${string}` | ''}` | `/whatsapp-contacts${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/favorites${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/appointment-detail`; params?: Router.UnknownInputParams; } | { pathname: `/appointments`; params?: Router.UnknownInputParams; } | { pathname: `/compare-properties`; params?: Router.UnknownInputParams; } | { pathname: `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/help-center`; params?: Router.UnknownInputParams; } | { pathname: `/property-details`; params?: Router.UnknownInputParams; } | { pathname: `/recently-viewed`; params?: Router.UnknownInputParams; } | { pathname: `/saved-searches`; params?: Router.UnknownInputParams; } | { pathname: `/schedule-visit`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/shared-property`; params?: Router.UnknownInputParams; } | { pathname: `/whatsapp-contacts`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
